DROP TABLE IF EXISTS assessment_center_exercise;
DROP TABLE IF EXISTS assessment_center;
DROP TABLE IF EXISTS screening; 
DROP TABLE IF EXISTS applicant;
DROP TABLE IF EXISTS form_item;
DROP TABLE IF EXISTS form;
DROP TABLE IF EXISTS job_requirement;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS organization;

DROP TYPE FORM_COMPONENT;
DROP TYPE FORM_CATEGORY;

DROP EXTENSION IF EXISTS "uuid-ossp";