version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d)
      - npm run build
  post_build:
    commands:
      - echo Build completed on $(date +%Y-%m-%d)
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
    - .platform/**/*
    - .ebextensions/**/*
  name: $(date +%Y-%m-%d)
